#!/usr/bin/env bash

AI_DEFAULT_PROMPT=$(cat <<'EOF'
You are a senior code reviewer for a pull request. The user message contains a
unified `git diff` (lines starting with `+` are added, lines starting with `-`
are removed).

Scope:
- Review only lines visible in the diff. Do not speculate about code that is
  not shown.
- Deprioritize purely cosmetic or generated changes (lockfiles, formatter-only
  diffs, vendored files). Still call out risky dependency or configuration
  changes (new vulnerable deps, wrong env vars, security-sensitive flags).
- If the diff contains no reviewable code changes, still emit the output
  template below with `Score: N/A` and a one-line explanation. Do not skip the
  template.

Priorities (highest to lowest):
1. Correctness and security bugs
2. Performance issues with measurable impact
3. Maintainability (naming, simplification, dead code, SOLID, edge cases)
4. Style nits — only if nothing higher-priority remains

Scoring rubric (anchor your score to these tiers):
- 90-100: Ship as-is. At most trivial nits.
- 70-89:  Minor improvements suggested. Non-blocking.
- 50-69:  Changes recommended before merge.
- 0-49:   Blocking issues (bugs, security, broken contracts).
- N/A:    No reviewable code in the diff.

Rules:
- Be concise. Use bullets, not paragraphs.
- Order feedback by severity, highest first.
- If a suggestion depends on context not visible in the diff, prefix it with
  "Assumes ...".
- Do not invent nits to fill space. "No issues found" is a valid review.
- Suggest code changes, not "add a comment explaining this."
- Assume high standards for production code.

Output Format (always use this exact structure):

<details>
<summary>Score: [0-100 or N/A]</summary>

Improvements:
- [Highest-severity issue first]
- [Next issue]
- ...

Suggested change for the most impactful issue (omit this block entirely if
score is 90+ or N/A):
```[language]
[replacement code]
```
</details>
EOF
)

# Resolve the system prompt in this priority order:
#   1. AI_PROMPT_OVERRIDE  - inline override (string)
#   2. AI_PROMPT_FILE      - file containing the prompt
#   3. AI_DEFAULT_PROMPT   - bundled default
ai::resolve_prompt() {
  if [[ -n "${AI_PROMPT_OVERRIDE:-}" ]]; then
    printf "%s" "$AI_PROMPT_OVERRIDE"
    return 0
  fi

  if [[ -n "${AI_PROMPT_FILE:-}" ]]; then
    if [[ ! -r "$AI_PROMPT_FILE" ]]; then
      utils::log_error "Prompt file '$AI_PROMPT_FILE' is missing or not readable."
      return 1
    fi
    cat "$AI_PROMPT_FILE"
    return 0
  fi

  printf "%s" "$AI_DEFAULT_PROMPT"
}

# Default upper bound for tokens generated by the model. Overridable via the
# AI_MAX_TOKENS env var (set from the action's `ai_max_tokens` input).
readonly AI_DEFAULT_MAX_TOKENS=8192

ai::max_tokens() {
  printf "%s" "${AI_MAX_TOKENS:-$AI_DEFAULT_MAX_TOKENS}"
}

# OpenAI's reasoning models (o-series, GPT-5 family) require
# `max_completion_tokens` instead of `max_tokens` and reject several legacy
# parameters. Detect by name prefix.
ai::is_openai_reasoning_model() {
  local -r model="$1"
  case "$model" in
    o1*|o3*|o4*|gpt-5*) return 0 ;;
    *) return 1 ;;
  esac
}

ai::prompt_model() {
  local -r git_diff="$1"

  case "$AI_PROVIDER" in
    "openai")
      ai::prompt_openai "$git_diff"
      ;;
    "claude")
      ai::prompt_claude "$git_diff"
      ;;
    *)
      utils::log_error "Unsupported AI provider: $AI_PROVIDER. Supported providers: openai, claude"
      ;;
  esac
}

ai::prompt_openai() {
  local -r git_diff="$1"
  local -r api_url="https://api.openai.com/v1/chat/completions"
  local -r max_tokens="$(ai::max_tokens)"
  local prompt
  prompt="$(ai::resolve_prompt)"

  local payload
  if ai::is_openai_reasoning_model "$AI_MODEL"; then
    payload=$(jq -n \
      --arg model "$AI_MODEL" \
      --arg prompt "$prompt" \
      --arg git_diff "$git_diff" \
      --argjson max_tokens "$max_tokens" \
      '{
        model: $model,
        max_completion_tokens: $max_tokens,
        messages: [
          {role: "system", content: $prompt},
          {role: "user", content: $git_diff}
        ]
      }')
  else
    payload=$(jq -n \
      --arg model "$AI_MODEL" \
      --arg prompt "$prompt" \
      --arg git_diff "$git_diff" \
      --argjson max_tokens "$max_tokens" \
      '{
        model: $model,
        max_tokens: $max_tokens,
        messages: [
          {role: "system", content: $prompt},
          {role: "user", content: $git_diff}
        ]
      }')
  fi

  local response http_code body
  response=$(curl -sSL -w $'\n%{http_code}' \
    --retry 3 --retry-delay 2 --retry-connrefused --max-time 180 \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $AI_API_KEY" \
    -d "$payload" \
    "$api_url")

  http_code="${response##*$'\n'}"
  body="${response%$'\n'*}"

  if [[ ! "$http_code" =~ ^2 ]]; then
    local message
    message=$(jq -r '.error.message // .error // .' <<< "$body" 2>/dev/null || printf "%s" "$body")
    utils::log_error "OpenAI request failed (HTTP $http_code): $message"
    return 1
  fi

  jq -r '.choices[0].message.content // empty' <<< "$body"
}

ai::prompt_claude() {
  local -r git_diff="$1"
  local -r api_url="https://api.anthropic.com/v1/messages"
  local -r max_tokens="$(ai::max_tokens)"
  local prompt
  prompt="$(ai::resolve_prompt)"

  local payload
  payload=$(jq -n \
    --arg model "$AI_MODEL" \
    --arg system "$prompt" \
    --arg git_diff "$git_diff" \
    --argjson max_tokens "$max_tokens" \
    '{
      model: $model,
      max_tokens: $max_tokens,
      system: $system,
      messages: [
        {role: "user", content: $git_diff}
      ]
    }')

  local response http_code body
  response=$(curl -sSL -w $'\n%{http_code}' \
    --retry 3 --retry-delay 2 --retry-connrefused --max-time 180 \
    -H "Content-Type: application/json" \
    -H "x-api-key: $AI_API_KEY" \
    -H "anthropic-version: 2023-06-01" \
    -d "$payload" \
    "$api_url")

  http_code="${response##*$'\n'}"
  body="${response%$'\n'*}"

  if [[ ! "$http_code" =~ ^2 ]]; then
    local message
    message=$(jq -r '.error.message // .error // .' <<< "$body" 2>/dev/null || printf "%s" "$body")
    utils::log_error "Claude request failed (HTTP $http_code): $message"
    return 1
  fi

  jq -r '.content[0].text // empty' <<< "$body"
}
