name: labeler

on: [pull_request]

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@4e3aa0f77f348c8066513d453515316ffa01a607 # v1.11.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ignore_file_deletions: 'true'
          files_to_ignore: 'README.md'
