name: labeler

on: [pull_request]

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@095a41fca88b8764fd9e008ad269bcdb82bb38b9 # v1.10.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ignore_file_deletions: 'true'
          files_to_ignore: 'README.md'
