name: labeler

on: [pull_request]

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@19c335e7695ba922de938806dd129f0a9b992644 # v1.12.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ignore_file_deletions: 'true'
          files_to_ignore: 'README.md'
