name: robin-ai-reviewer

on: [pull_request]

jobs:
  robin-ai-reviewer:
    runs-on: ubuntu-latest
    name: Review the open PR
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
